<a href="https://colab.research.google.com/github/25prateek/google_colab/blob/master/numpy1t.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a=np.array([2,4,76,8,34,5])

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([12,17,28,199,14])

In [0]:
a

array([ 2,  4, 76,  8, 34,  5])

In [0]:
b

array([ 12,  17,  28, 199,  14])

In [0]:
a[1]

4

In [0]:
b[0]

12

In [0]:
a+b

array([ 14,  21, 104, 207,  48,  21])

In [0]:
a+b

array([ 14,  21, 104, 207,  48,  21])

In [0]:
b

array([ 12,  17,  28, 199,  14])

In [0]:
b=np.array([12,17,28,199,14,16])

In [0]:
a+b

array([ 14,  21, 104, 207,  48,  21])

In [0]:
a+2

array([ 4,  6, 78, 10, 36,  7])

In [0]:
c=np.array([[1,2,3],[2,3,4],[2,3,4]])

In [0]:
c

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4]])

In [0]:
c[0]

array([1, 2, 3])

In [0]:
c[0][0]

1

In [0]:
y=c+7

In [0]:
y

array([[ 8,  9, 10],
       [ 9, 10, 11],
       [ 9, 10, 11]])

In [0]:
c*2

array([[2, 4, 6],
       [4, 6, 8],
       [4, 6, 8]])

In [0]:
c**3

array([[ 1,  8, 27],
       [ 8, 27, 64],
       [ 8, 27, 64]])

In [0]:
y

array([[ 8,  9, 10],
       [ 9, 10, 11],
       [ 9, 10, 11]])

In [0]:
z=np.array([[1,5],[4,6],[4,5],[1,4]])

In [0]:
z

array([[1, 5],
       [4, 6],
       [4, 5],
       [1, 4]])

In [0]:
c

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4]])

In [0]:
c.shape

(3, 3)

In [0]:
z.shape

(4, 2)

In [0]:
z[0:2]

array([[1, 5],
       [4, 6]])

In [0]:
z[0:]

array([[1, 5],
       [4, 6],
       [4, 5],
       [1, 4]])

In [0]:
z[0:,1]

array([5, 6, 5, 4])

In [0]:
z[:,0]

array([1, 4, 4, 1])

In [0]:
c[:,2]

array([3, 4, 4])

In [0]:
c[:,2:0]

array([], shape=(3, 0), dtype=int64)

In [0]:
z[:,0:2]

array([[1, 5],
       [4, 6],
       [4, 5],
       [1, 4]])

In [0]:
z[:,0:1]

array([[1],
       [4],
       [4],
       [1]])

In [0]:
c

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4]])

In [0]:
c[0:,[0,2]]


array([[1, 3],
       [2, 4],
       [2, 4]])

In [0]:
c[0:,[1,2]]


array([[2, 3],
       [3, 4],
       [3, 4]])

In [0]:
2



2

In [0]:
b=np.array([[1,9,7],[3,2,8],[4,5,6],[2,9,0]])


In [0]:
b


array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [0]:
b[:,1]

array([9, 2, 5, 9])

In [0]:
b[:,2]

array([7, 8, 6, 0])

In [0]:
b[[1,2],1]



array([2, 5])

In [0]:
b[1:,2]

array([8, 6, 0])

In [0]:
b[1:,[0,2]]


array([[3, 8],
       [4, 6],
       [2, 0]])

In [0]:
a

array([ 2,  4, 76,  8, 34,  5])

In [0]:
b

array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [0]:
c

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4]])

In [0]:
z

array([[1, 5],
       [4, 6],
       [4, 5],
       [1, 4]])

In [0]:
y

array([[ 8,  9, 10],
       [ 9, 10, 11],
       [ 9, 10, 11]])

In [0]:
z.reshape(4,2)

array([[1, 5],
       [4, 6],
       [4, 5],
       [1, 4]])

In [0]:
z.reshape(2,4)

array([[1, 5, 4, 6],
       [4, 5, 1, 4]])

In [0]:
np.zeros((16,32))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [0]:
np.full((4,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [0]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '_distributor_init',
